Xcframework prebuilt binaries
Carthage/Carthage pull request #3123
Opened 2021-02-05 01:38 UTC by igstewart3

This PR adds the ability to retrieve XCFramework prebuilt binaries. It installs them into the Carthage/Build folder and skips any Xcode.swift steps that involve checking the architecture.

It could probably use a wee bit of guidance from someone more familiar with the project to ensure I haven't missed something important.

I have tested this on a local project and was successfully able to install XCFramework binaries, as well as regular Framework binaries from a previous release.

Note: I have not been able to run the unit tests yet due to some Swift compile errors I haven't been able to resolve.

2021-02-09 08:52 UTC, sebskuse commented
I've tested this against the latest https://github.com/aws-amplify/aws-sdk-ios, which provides prebuilt XCFramework binaries and this works as expected!

Using Carthage 0.37.0 we see:

```
*** Fetching aws-sdk-ios
*** Checking out aws-sdk-ios at "2.22.2"
*** No cache found for aws-sdk-ios, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/c0/068z__x16p15190541prsvkm0000gp/T/carthage-xcodebuild.RnWKmY.log
*** Downloading aws-sdk-ios.framework binary at "AWS SDK for iOS 2.22.2"
***  Skipped installing aws-sdk-ios.framework binary due to the error:
	"Invalid archive - Found multiple frameworks with the same unarchiving destination:
* 	file:///var/folders/c0/068z__x16p15190541prsvkm0000gp/T/carthage-archive.IXODoQ/AWSLogs.xcframework/ios-arm64_i386_x86_64-simulator/AWSLogs.framework/
	file:///var/folders/c0/068z__x16p15190541prsvkm0000gp/T/carthage-archive.IXODoQ/AWSLogs.xcframework/ios-arm64_armv7/AWSLogs.framework/ 
		to:
	file:///Path/To/Carthage/Build/iOS/AWSLogs.framework/

... repeat for every framework

Falling back to building from the source
```

Using this branch we see:

```
*** Fetching aws-sdk-ios
*** Checking out aws-sdk-ios at "2.22.2"
*** No cache found for aws-sdk-ios, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/c0/068z__x16p15190541prsvkm0000gp/T/carthage-xcodebuild.ll5AoF.log
*** Downloading aws-sdk-ios.framework binary at "AWS SDK for iOS 2.22.2"
```

And the prebuilt frameworks are in the expected folder.

2021-02-10 00:30 UTC, dmiluski commented
Hi @igstewart3 ,

I just ran into this today with a similar hiccup with AWS (wowza **HUGE** install times). Thanks for kicking off the effort.

I'm not a repo owner/maintainer, but wanted to give some notes as I just started dabbling with this too:

Reading through I noticed this used string literals and bool logic to concatenate behaviors. Skimming the implementation, I noticed:

```
/// Describes the type of product built by an Xcode target.
public enum ProductType: String {
	/// A framework bundle.
	case framework = "com.apple.product-type.framework"

	/// A static library.
	case staticLibrary = "com.apple.product-type.library.static"

	/// A unit test bundle.
	case testBundle = "com.apple.product-type.bundle.unit-test"
```

And was wondering if perhaps xcframework should be included as a sibling here? Allowing for the use of this definition for path? Allowing for a model to drive potential differentiation rather than bool checks?

```
/// Framework Suffix
public enum FrameworkSuffix: String {

    /// Dynamic Framework
    case dynamic = "framework"

    /// XCFramework
    case xcode = "xcframework"
}
```

2021-02-15 03:48 UTC, igstewart3 commented
> Hi @igstewart3 ,
> 
> I just ran into this today with a similar hiccup with AWS (wowza **HUGE** install times). Thanks for kicking off the effort.
> 
> I'm not a repo owner/maintainer, but wanted to give some notes as I just started dabbling with this too:
> 
> Reading through I noticed this used string literals and bool logic to concatenate framework download behaviors. Skimming the implementation, I noticed:
> 
> ```
> /// Describes the type of product built by an Xcode target.
> public enum ProductType: String {
> 	/// A framework bundle.
> 	case framework = "com.apple.product-type.framework"
> 
> 	/// A static library.
> 	case staticLibrary = "com.apple.product-type.library.static"
> 
> 	/// A unit test bundle.
> 	case testBundle = "com.apple.product-type.bundle.unit-test"
> ```
> 
> And was wondering if perhaps xcframework should be included as a sibling here? Allowing for the use of this definition for path? Allowing for a model to drive potential differentiation rather than bool checks?
> 
> ```
> /// Framework Suffix
> public enum FrameworkSuffix: String {
> 
>     /// Dynamic Framework
>     case dynamic = "framework"
> 
>     /// XCFramework
>     case xcode = "xcframework"
> }
> ```

Good shout, I'll take a look at tidying that up 👍

2021-02-23 06:29 UTC, finik commented
I can confirm as well, the fix in this branch works, please merge and release this ASAP, this blocks some frameworks from being properly distributed. Thanks

2021-02-23 19:58 UTC, igstewart3 commented on Source/CarthageKit/Project.swift
> +        .concat(filesInDirectory(directoryURL, "com.apple.xcframework"))
Done 👍

2021-02-23 19:59 UTC, igstewart3 commented on Source/CarthageKit/Xcode.swift
> +    guard isNotXCFramework(packageURL) else {
Done 👍

2021-02-23 19:59 UTC, igstewart3 commented on Source/CarthageKit/Xcode.swift
> +    guard isNotXCFramework(packageURL) else {
Done for all changes made in the PR 👍

2021-02-28 01:58 UTC, elliottwilliams requested changes
First off, thanks so much for your contribution! I think this makes a lot of sense and is obviously something we need to support.

Aside from the suggestions below, we need to handle `checkFrameworkCompatibility` correctly. Since it's possible to build an xcframework with `-allow-internal-distribution`, it's possible to have swiftmodules in the xcframework that aren't compatible with the machine they're downloaded to. This patch should fix it, LMK if there's anything I can clarify:
[carthage-3123-additions.patch.txt](https://github.com/Carthage/Carthage/files/6056150/carthage-3123-additions.patch.txt)

2021-03-01 01:38 UTC, igstewart3 commented on Source/CarthageKit/Project.swift
> +																			 frameworkNameAndExtension: $0.lastPathComponent) }
Done 👍

2021-03-01 01:38 UTC, igstewart3 commented on Source/CarthageKit/Project.swift
> +				return FrameworkSuffix.from(string: pathExtension).error == nil
Done 👍

2021-03-01 01:39 UTC, igstewart3 commented on Source/CarthageKit/Project.swift
> +				case .xcframework:
Done 👍

2021-03-01 01:52 UTC, igstewart3 commented on Source/CarthageKit/Xcode.swift
> +}
Several of these methods are called when installing the prebuilt XCFrameworks and fail due to not being able to find the executableURL in the bundle in `binaryURL(packageUrl:)`. We could look into adding a custom case for XCFrameworks like is already in place for .dSYM and (and changing to return an array of URLs), but many of these processes (stripping architectures and debug symbols) don't necessarily make sense for an XCFramework anyway.

2021-03-01 02:00 UTC, igstewart3 commented
@elliottwilliams Thanks very much for the feedback! I've implemented most of it, including the patch you provided. I think only the XCFramework guard cases in `Xcode.swift` still need to be resolved. They definitely allow the prebuilt binary to be installed successfully but they do feel a little clumsy, keen to hear your thoughts on that.

2021-03-03 06:10 UTC, elliottwilliams commented
> @elliottwilliams Thanks very much for the feedback! I've implemented most of it, including the patch you provided. I think only the XCFramework guard cases in `Xcode.swift` still need to be resolved. They definitely allow the prebuilt binary to be installed successfully but they do feel a little clumsy, keen to hear your thoughts on that.

@igstewart3 I think I got it working – we just need to avoid calling into the dSYM/bcsymbolmap logic higher up. This is similar to [what we do on the `build` side](https://github.com/Carthage/Carthage/blob/709b82a2db586f419b18fa21e53ea0cd4ab70745/Source/CarthageKit/Xcode.swift#L776-L784), where we conditionally avoid calling any debug symbols merging code when making an xcframework. See the commit I just pushed :)

I confirmed this works with a `github "aws-amplify/aws-sdk-ios"` Cartfile, but LMK if there's anything else you're noticing.

2021-03-03 19:27 UTC, igstewart3 commented
@elliottwilliams Nice! Good fix, that looks a lot tidier. Everything seems to be working in my tests as well 👍

2021-03-05 01:56 UTC, elliottwilliams approved these changes
Sounds good! Going to give the other maintainers a moment to review if they'd like.

2021-03-08 12:31 UTC, ozgur approved these changes

2021-03-19 18:27 UTC, merged